apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-app-with-sidecar
spec:
  components:
    - name: web
      type: webservice
      properties:
        image: oamdev/hello-world:v2
        ports:
          - port: 8000
      traits:
        - type: sidecar
          properties:
            name: frp-client
            image: oamdev/frpc:0.43.0
            env:
              - name: server_addr
                value: "47.114.96.241"
              - name: server_port
                value: "9090"
              - name: local_port
                value: "8000"
              - name: connect_name
                value: "my_web"
              - name: local_ip
                value: "127.0.0.1"
              - name: remote_port
                value: "6002"
